# EEG
Ophthalmic_procedure: False
Send_EEG_trigg: False

# view parameters
Screen_color: "black"
Text_color: "white"
Text_size: 60

# flanker parameters
Fixation_size: 20
Flanker_size: 50
Font: "Noto Mono"
Orientation: "vertical"

# cue definition
Cues: [5, 100]
# Cues: null    # if left as null, no cues will be shown


# times
Cue_show_time: [1.000, 1.000]       # this has no effect of Cues is null
Empty_screen_1_show_time: [0.100, 0.100]    # this has no effect of Cues is null
Fixation_show_time: [0.600, 0.800]
Flanker_show_time: [0.035, 0.035]   # this one is optional
Target_show_time: [0.200, 0.200]
Empty_screen_2_show_time: [0.600, 0.600]

# reaction keys
# first one is for left response, second one is for right response
Keys: [mouse_left, mouse_right]
# Keys: [lshift, rshift]

# experiment structure
Experiment_blocks: [
    {type: break, file_name: instruction.txt},
    {type: training, number_of_trials: 8, ratio_of_congruent: 0.5, ratio_of_first_cue: 0.5},
    {type: break, file_name: end_training.txt},
    {type: experiment, number_of_trials: 8, ratio_of_congruent: 0.5, ratio_of_first_cue: 0.5},
    {type: break, file_name: end.txt}]
