Procedure: "Diamond task"

# * EEG
Send_EEG_trigg: False

# * view parameters
Screen_color: -0.25    # -1 is black, 1 is white, -0.25 corresponds to RGB 96
Text_color: "black"
Text_size: 60
Text_font: "Arial"
Info_size: 108    # 180
Arrows_size: 300  # 500

# * times
# Empty_screen_between_trials: [0.900, 1.500, 0.100]   # min, max, step
# Fixation_show_time: [2.000, 2.000]                   # min, max
# Photo_show_time: [0.005, 0.005]
# Diamond_info_show_time: [2.000, 2.000]
# Feedback_show_time: [1.500, 1.500]
Empty_screen_between_trials: [1.000, 1.000, 0.100]   # min, max, step
Fixation_show_time: [0.000, 0.000]                   # min, max
Photo_show_time: [0.005, 0.005]
Diamond_info_show_time: [1.000, 1.000]
Feedback_show_time: [1.500, 1.500]

# * optional steps
Show_photo: False
Rate_arousal: True
Rate_valence: True
Show_feedback: False

# * reaction keys
Keys: "joystick"     # "joystick" or "arrows"
Slider_speed: 2      # if joystick is used to move the slider, chosse slider speed here

# * experiment structure
Experiment_blocks: [
    {type: break, file_name: instruction.txt},
    # {type: training, number_of_trials: 20, ratio_of_congruent: 0.8, ratio_of_first_cue: 0.5},
    # {type: break, file_name: end_training.txt},
    {type: experiment, info_file: "trial_list_S1_C.xlsx"},
    {type: break, file_name: break1.txt},
    {type: experiment, info_file: "trial_list_S1_NC.xlsx"},
    {type: break, file_name: end.txt}]
