Procedure: "Diamond task"

# * EEG
Send_EEG_trigg: False

# * view parameters
Screen_color: -0.25    # -1 is black, 1 is white, -0.25 corresponds to RGB 96
Text_color: "black"
Text_size: 0.04
Text_font: "Arial"
Info_size: 0.075       # size of text cues
Arrows_size: 0.2

# * times
# Empty_screen_between_trials: [0.900, 1.500, 0.100]   # min, max, step
# Fixation_show_time: [2.000, 2.000]                   # min, max
# Photo_show_time: [0.005, 0.005]   # note that actually this will be much more than 5 ms, because of larger monitor refresh rate
# Diamond_info_show_time: [2.000, 2.000]
# Feedback_show_time: [1.500, 1.500]
Empty_screen_between_trials: [1.000, 1.000, 0.100]   # min, max, step
Fixation_show_time: [0.200, 0.200]                   # min, max
Photo_show_time: [0.500, 0.500]   # note that actually this will be much more than 5 ms, because of larger monitor refresh rate
Diamond_info_show_time: [1.000, 1.000]
Feedback_show_time: [1.500, 1.500]

# * optional steps
Show_image: True
Rate_arousal: True
Rate_valence: True
Show_feedback: True
#################################
# Images_directory: "input_data/diamond_task/IAPS"   # this is only needed if Show_image is True
Images_directory: "input_data/diamond_task/testImages_artphoto"    # from https://www.imageemotion.org/
#################################
Feedback_good: "dobry wybór"   # this is only needed if Show_feedback is True
Feedback_bad: "zły wybór"


# * reaction keys
Keys: "arrows"     # "joystick" or "arrows"
Slider_speed: 2      # if joystick is used to move the slider, chosse slider speed here

# * experiment structure
Experiment_blocks: [
    {type: break, file_name: instruction.txt},
    # {type: training, number_of_trials: 20, ratio_of_congruent: 0.8, ratio_of_first_cue: 0.5},
    # {type: break, file_name: end_training.txt},
    {type: experiment, info_file: "trial_list_S1_C_test_slides.xlsx"},   # from https://www.imageemotion.org/
    {type: break, file_name: break1.txt},

    {type: experiment, info_file: "trial_list_S1_C.xlsx"},
    {type: break, file_name: break1.txt},
    {type: experiment, info_file: "trial_list_S1_NC.xlsx"},
    {type: break, file_name: end.txt}]
