Procedure: "Diamond task"

# * EEG
Send_EEG_trigg: False

# * view parameters
Screen_number: -1       # 0 is built-in; 1 is external; -1 means "last", so it will be external if external is connected, otherwise built-in
Screen_color: -0.25    # -1 is black, 1 is white, -0.25 corresponds to RGB 96
Text_color: "black"
Text_size: 0.03        # this is size of the text in the instructions
Procedure_text_size: 0.04    # this is size of the text in the procedure
Text_font: "Arial"
Info_size: 0.075       # size of text cues
Arrows_size: 0.2
Self_assessment_manikin_size: [0.1449, 0.1561]  # size of the manikins is 207x223 pixels
Self_assessment_manikin_spacing: 0.225

# * times
Empty_screen_between_trials: [0.900, 1.500, 0.100]   # min, max, step
Fixation_show_time: [2.000, 2.000, 0.001]
Photo_show_time: [0.005, 0.005, 0.001]   # note that actually this will be much more than 5 ms, because of larger monitor refresh rate
Diamond_info_show_time: [2.000, 2.000, 0.001]
Blank_between_choice_and_confidence_rating: [0.500, 0.500, 0.100]
Blank_between_confidence_rating_and_feedback: [0.500, 0.500, 0.100]
Feedback_show_time: [1.500, 1.500, 0.001]

# * optional steps
Show_images: True
Rate_arousal: True
Rate_valence: True
Show_feedback: True
#################################
Images_directory: "input_data/diamond_task/IAPS/IMAGES"   # this is only needed if Show_images is True
Image_size: [1.333333, 1]    # width, height
#################################
Feedback_good: "dobry wybór"   # this is only needed if Show_feedback is True
Feedback_bad: "zły wybór"


# * reaction keys
Keys: "arrows"     # "joystick" or "arrows"
Slider_speed: 2      # if joystick is used to move the slider, chosse slider speed here

# * experiment structure
Experiment_blocks: [
    {type: break, file_name: "diamond_task/instruction1.txt"},
    {type: experiment, info_file: "trial_list_S1_C_with_images.xlsx"},   # from https://www.imageemotion.org/
    {type: break, file_name: break1.txt},
]
