Procedure: "Flanker task"

# * EEG
Ophthalmic_procedure: False
Send_EEG_trigg: False

# * view parameters
Screen_color: "black"
Text_color: "white"
Text_size: 0.055
Flanker_size: 0.092
Text_font: "Arial"

# * flanker parameters
Flanker_font: "Noto Sans Mono"   # FreeMono, Noto Sans Mono, DejaVu Sans Mono
Flanker_size: 0.092
Orientation: "horizontal"
Right_char: ">"
Left_char: "<"
Fixation_char: "+"
Flanker_position: [0, 0] # this is needed to align arrows at the center of the screen

# * cue definition
Show_cues: True
Cues: [5, 100]

# * feedback  definition
Show_feedback: False

# * times
Empty_screen_between_trials: [0.0, 0.0]
Cue_show_time: [2.000, 2.000]
Empty_screen_after_cue_show_time: [0.100, 0.100]
Fixation_show_time: [0.600, 0.800]
Target_show_time: [0.200, 0.200]
Blank_screen_for_response_show_time: [1.700, 2.300]
Empty_screen_after_response_show_time: [0.0, 0.0]

# if this is False, we will end response time windw immediately after response, and carry on
# if True, we will wait until the whole window ends even after the response, like in Hajcak2005
Use_whole_response_time_window: True

# * reaction keys
# first one is for left response, second one is for right response
Keys: [mouse_left, mouse_right]

# * experiment structure
Experiment_blocks: [
    {type: break, file_name: instruction.txt},
    {type: training, number_of_trials: 8, ratio_of_congruent: 0.5, ratio_of_first_cue: 0.5},
    {type: break, file_name: end_training.txt},

    {type: experiment, number_of_trials: 8, ratio_of_congruent: 0.5, ratio_of_first_cue: 0.5},
    {type: break, file_name: break1.txt},

    {type: break, file_name: end.txt}]
