Procedure: "Flanker task"

# * EEG
Ophthalmic_procedure: False
Send_EEG_trigg: False
Actiview_reminder: True

# * view parameters
Screen_color: "black"
Text_color: "white"
Text_size: 0.04
Flanker_size: 0.092
Text_font: "Arial"

# * flanker parameters
Fixation: "+.png"
Arrow_left: "bracket_leftpng"
Arrow_right: "bracket_right.png"
Fixation_size: 0.04
Flanker_size: [0.05, 0.05]
Flanker_spacing: 0.04
Orientation: "horizontal"

# * cue definition
Show_cues: True
Cues: [5, 100]
Cue_size: 0.055

# * feedback  definition
Show_feedback: False

# * times
Empty_screen_between_trials: [0.0, 0.0]
Cue_show_time: [2.000, 2.000]
Empty_screen_after_cue_show_time: [0.100, 0.100]
Fixation_show_time: [0.600, 0.800]
Target_show_time: [0.200, 0.200]
Blank_screen_for_response_show_time: [1.700, 2.300]
Empty_screen_after_response_show_time: [0.0, 0.0]

# if this is False, we will end response time windw immediately after response, and carry on
# if True, we will wait until the whole window ends even after the response, like in Hajcak2005
Use_whole_response_time_window: True

# * reaction keys
# first one is for left response, second one is for right response
Keys: [mouse_left, mouse_right]

# * experiment structure
Experiment_blocks: [
    {type: break, file_name: instruction.txt},
    {type: training, number_of_trials: 8, ratio_of_congruent: 0.5, ratio_of_first_cue: 0.5},
    {type: break, file_name: end_training.txt},

    {type: experiment, number_of_trials: 8, ratio_of_congruent: 0.5, ratio_of_first_cue: 0.5},
    {type: break, file_name: break1.txt},

    {type: break, file_name: end.txt}]
