Procedure: "Monetary Incentive Delay"

# * EEG
Ophthalmic_procedure: False     # this is currently not supported
Send_EEG_trigg: False
Actiview_reminder: True

# * view parameters
Screen_color: -0.2
Text_color: "black"
Text_size: 0.04
Text_font: "Arial"

# * stimulus definition
Stimuli: {
    fixation: ["+.png", 0.03],
    cue_incentive: ["dollar.png", 0.06],
    cue_neutral: ["hash.png", 0.06],
    feedback_neutral: ["0_bold.png", 0.06],
    circle: ["circle.png", 0.12],
    target: ["square.png", 0.12],
    feedback_good: ["smiley_face.png", 0.12],
    feedback_bad: ["sad_face.png", 0.12],
}

# * times
Empty_screen_between_trials: [0.800, 0.800]
Fixation_show_time: [0.500, 0.500]
Cue_show_time: [0.400, 0.400]
Target_anticipation_time: [2.000, 2.500]
Target_initial_show_time: 0.400
Response_timeout: 1.000
Empty_screen_between_response_and_feedback: [1.300, 1.300]
Feedback_show_time: [1.000, 1.000]

# * reaction keys
Keys: [rctrl]
# Keys: [num_delete]

# * experiment structure
Experiment_blocks: [
    {type: break, file_name: instruction.txt},
    {type: training, number_of_trials: 10, cue_incentive_ratio: 0.8},

    {type: break, file_name: end_training.txt},
    {type: experiment, number_of_trials: 35, cue_incentive_ratio: 0.7},
    {type: break, file_name: monetary_incentive_delay/break1.txt},
    {type: experiment, number_of_trials: 35, cue_incentive_ratio: 0.7},
    {type: break, file_name: monetary_incentive_delay/break2.txt},
    {type: experiment, number_of_trials: 35, cue_incentive_ratio: 0.7},
    {type: break, file_name: monetary_incentive_delay/break3.txt},
    {type: experiment, number_of_trials: 35, cue_incentive_ratio: 0.7},
    {type: break, file_name: end.txt}
]