Procedure: "Topological task"
Ask_for_experiment_version: True
Num_random_conditions: 2

# EEG
# Send_EEG_trigg: True
# Actiview_reminder: True
Send_EEG_trigg: False
Actiview_reminder: False

Screen_number: 0  # maybe todo: remove later?
    
# view parameters
Text:
    height: 0.037
    font: "Arial"
    color: "black"
Screen_color: "white"
Figure_size: [null, 0.5]
Fixation_size: 0.028
Word_size: 0.1
Sizes: {}
Yes_no_stim_distance: 0.1
Yes_no_stim_height: 0.037

# times
Pre_question_show_time: 2
First_fixation_show_time: 0.8
Image_show_time: 3
Second_fixation_show_time: 0.8
Word_show_time: 1
Maximal_response_time: 3
Third_fixation_show_time: 0.8

# reaction keys
key_names:
    lctrl: "LEWY CONTROL"
    rctrl: "PRAWY CONTROL"

