Procedure: "Topological task"
Ask_for_experiment_version: True

# EEG
# Send_EEG_trigg: True  # todo change back
# Actiview_reminder: True  # todo change back
Send_EEG_trigg: False
Actiview_reminder: False
    
Screen_number: 1  # todo remove it later

# view parameters
Screen_color: "white"
Text_size: 0.037
Text_font: "Arial"
Text_color: "black"
Figure_size: 0.5
Fixation_size: 0.028
Particle_size: 0.1
Sizes: {}


# times
Pre_question_show_time: 2
First_fixation_show_time: 0.8
Image_show_time: 3
Second_fixation_show_time: 0.8
Particle_show_time: 1
Maximal_response_time: 3
Third_fixation_show_time: 0.8



# reaction keys
A_Keys: {yes_key: "lctrl", no_key: "rctrl"}
B_Keys: {yes_key: "rctrl", no_key: "lctrl"}
key_names:
    lctrl: "LEWY CONTROL"
    rctrl: "PRAWY CONTROL"

