Observer: Patrycja

# EEG
Ophthalmic_procedure: False
Send_EEG_trigg: False

# view parameters
Screen_color: "black"
Text_color: "white"
Text_size: 40
Fixation_size: 30
Flanker_size: 100

# times
Fixation_show_time: [0.5, 0.5]
Target_show_time: [1, 1]
Empty_screen_show_time: [4, 4]

# reaction keys
# first one is for left response, second one is for right response
Keys: [mouse_left, mouse_right]
# Keys: [lshift, rshift]

# experiment structure
Experiment_blocks: [
    {type: training, number_of_congruent_trials: 4, number_of_incongruent_trials: 2},
    {type: break, file_name: end_training1.txt},
    {type: experiment, number_of_congruent_trials: 4, number_of_incongruent_trials: 2},
    {type: break, file_name: end.txt}]
